package:
    name: coecms-util
    version: {{ GIT_DESCRIBE_TAG }}

source:
    git_url: ../

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
    run:
        - python
        - netcdf4
        - xarray
        - scipy
        - numpy
        - cdo

test:
    requires:
        - pytest
    source_files:
        - setup.cfg
        - test
    commands:
        - py.test
    imports:
        - coecms
